#!/usr/bin/python
import rospy
from fault_observer.observer_class import Observer

def main():
    rospy.init_node('observer_node')
    obs = Observer()

    while not rospy.is_shutdown():
        obs.cycle()
        rate = rospy.Rate(10)
        rate.sleep()

if __name__ == "__main__":
    main()
