#!/usr/bin/python
import rospy
from fault_observer.observer_class import Observer

def main():
    rospy.init_node('observer_node')
    obs = Observer()
    rospy.spin()

if __name__ == "__main__":
    main()
